Update to new NetQASM interface
QuTech-Delft/squidasm pull request #8
Opened 2022-02-17 15:50 UTC by bvdvecht

Closes #6

2022-02-24 18:39 UTC, bvdvecht commented
Blocked until https://github.com/QuTech-Delft/netqasm/pull/14 is merged.

2022-03-03 17:33 UTC, bvdvecht commented
Unblocked now that https://github.com/QuTech-Delft/netqasm/pull/14 has been merged.

2022-03-04 16:17 UTC, QFer requested changes

2022-03-04 16:17 UTC, QFer commented on squidasm/sim/stack/processor.py
> -    def _interpret_qalloc(self, app_id: int, instr: core.QAllocInstruction) -> None:
I don't get the move to the (abstract) base class for this method. The NVProcessor has its own implementation, so you could have kept it an abstract method (in the sense no implementation in the abstract base class Processor) and another specific implementation in GenericProcessor.

2022-03-04 16:17 UTC, QFer commented on examples/stack/bqc/example_bqc_nv.py
> +PI_OVER_2 = math.pi / 2
You just defined math.pi as PI: why not: PI / 2

2022-03-04 16:17 UTC, QFer commented on examples/stack/bqc/example_bqc_nv.py
> +    # num_times = 1
better delete these 2 lines

2022-03-15 13:45 UTC, bvdvecht commented on squidasm/sim/stack/processor.py
> -    def _interpret_qalloc(self, app_id: int, instr: core.QAllocInstruction) -> None:
The implementation that is now in the base Processor class is expected to be re-used by new derived classes of Processor in the future. So in a way this is preparing for adding new Processor subclasses and not having to add the same implementation of `_interpret_qalloc` in those.

2022-03-15 13:46 UTC, bvdvecht commented on examples/stack/bqc/example_bqc_nv.py
> +PI_OVER_2 = math.pi / 2
I think this is mostly a difference in taste. Or do you have a concrete reason to prefer one way of writing over the other?

2022-03-15 13:47 UTC, bvdvecht commented on examples/stack/bqc/example_bqc_nv.py
> +    # num_times = 1
Done

2022-03-17 07:38 UTC, QFer approved these changes

2022-03-17 10:35 UTC, merged